// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "azure" {
    version = "latest"
  }

  connection {
    dsn = "postgres://postgres:pass@localhost:5432/postgres?sslmode=disable"
  }
}

// All Provider Configurations

provider "azure" {
  configuration {
    // Optional. if you not specified, cloudquery tries to access all subscriptions available to tenant
    // subscriptions = ["<YOU_SUBSCRIPTION_ID_HERE>"]
  }

  // list of resources to fetch
  resources = [
    "*"
  ]
}
