kind: source
spec:
  name: azure
  path: cloudquery/azure
  version: "v15.0.0" # latest version of azure plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v8.6.4" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
