kind: source
spec:
  name: azure
  path: cloudquery/azure
  version: "v1.3.2" # latest version of azure plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v1.6.1" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
